### ISSUE TITLE
makeTcpReceiver should not be based on a separator

### ISSUE THREAD

**Issue by DavidBruant** [anthill/pheromon#13]
Separators are a recipe for security issues. 
We should be using lengthed-messages. Doesn't TPC have a built-in message semantics?

The separator as argument is even worse. If we were to keep a separator, we should force it with a constant.

**Comment by vallettea** [comment]
Hum not clear, we though so with @4rzael but in practice we saw some messages that where cut in weird manner.
Anyway MQTT will solve this cleanly.

**Comment by iOiurson** [comment]
MQTT is now used, so this issue is deprecated.
