### ISSUE TITLE
About using MQTT

### ISSUE THREAD

**Issue by vallettea** [anthill/pheromon#24]
Looking at [opensensors.io/](https://opensensors.io/] I'm more and more convinced we should use MQQT between sensors and broker.

MQTT is a machine-to-machine (M2M)/"Internet of Things" connectivity protocol. It was designed as an extremely lightweight publish/subscribe messaging transport. It is useful for connections with remote locations where a small code footprint is required and/or network bandwidth is at a premium.

+ MQTT implements pub/sub that will clean a lot the processing of different streams of data*
+ MQTT will take care of sending a message even if the connexion is intermittent
+ topics are hierarchical
+ TCP/IP port 1883 is reserved with IANA for use with MQTT 
+ encryption over ssl possible but not implemented in the protocole itself
+ [nodejs mqtt lib](https://www.npmjs.com/package/mqtt) is well developed
+ [mosca](https://github.com/mcollina/mosca) is a nodejs broker that looks good also
+ opens the door to mesh networking

* this question arrises with the question of protobuf: each measurement type should have its own encode/decode functions. If you bind those to a topic of the pub/sub system it cleanly wires the flows independently and offers a good abstraction to push any kind of data.

![screen shot 2015-09-18 at 08 48 07](https://cloud.githubusercontent.com/assets/371303/9953547/1064a8f2-5de2-11e5-8d8e-1ded23267329.png)

![screen shot 2015-09-18 at 08 49 00](https://cloud.githubusercontent.com/assets/371303/9953560/23cb39ec-5de2-11e5-9eb9-0e42fc692133.png)

**Comment by iOiurson** [comment]
Closed by #40
