### ISSUE TITLE
gulp dev doesn't build

### ISSUE THREAD

**Issue by vallettea** [anthill/pheromon#3]
When you start the project from scratch the watch task never happens and thus you have no bundle.
We should add a build.

**Comment by DavidBruant** [comment]
Maybe we can have a `gulp start` which does build + dev and a `gulp dev` as it is currently (only up + watch)

**Comment by iOiurson** [comment]
Can smb confirm this was solved by #34 ?

**Comment by vallettea** [comment]
yes there is a build in gulp file
