### ISSUE TITLE
Make pheromon neutral about what's being measured

### ISSUE THREAD

**Issue by DavidBruant** [anthill/pheromon#33]
Nice move on https://github.com/anthill/pheromon/blob/f94360f14515a7e13f8afcd4681ecd5210601da2/database/management/createTables.sql#L57 but it's not enough. We cannot be sure a `real[]` is generic enough for all purposes. `text` or `bytea` may be more appropriate.

Also, an index needs to be added on the `type` column... well `measurement_date` and `sensor_id` too I guess.

**Comment by DavidBruant** [comment]
Should the `type` belong in the sensor rather than the measurement?

**Comment by iOiurson** [comment]
Dumb question: what's an index in a DB ?
And the `type` should belong to the measurement, because one sensor can technically have different ways to measure (wifi and bluetooth for instance).

**Comment by DavidBruant** [comment]
> And the type should belong to the measurement, because one sensor can technically have different ways to measure (wifi and bluetooth for instance).

Given they're *sensing* different signals, aren't they different *sensors*?
But they belong to the same hardware board with the same network interface. Maybe we need to work on this point. Is a sensor what senses or what discusses with the pheromon back-end? (I have no strong opinion right now)

> Dumb question: what's an index in a DB ?

https://en.wikipedia.org/wiki/Database_index ;-) (summary is enough. Ask details to @SergeBredin otherwise)

**Comment by iOiurson** [comment]
A sensor is linked to a SIM id, so basically everything that's physically connected to that SIM id belongs to the same sensor. So the type should belong to the measurement.
@vallettea any thoughts ?

**Comment by vallettea** [comment]
No I don't think they should be different sensors. On sensor (or should I say an ant) can measure multiple things and the benefit of mqtt is that the ant registers at N topics for N measurements.

**Comment by iOiurson** [comment]
Some of the work is handled by #34, it might not be enough though

**Comment by iOiurson** [comment]
The work on PR #55 participates in this issue.

**Comment by iOiurson** [comment]
Apart from https://github.com/anthill/pheromon/blob/master/api/maestro.js#L216-L227 and the 6bin 'back route' (see https://github.com/anthill/pheromon/issues/96), pheromon is now totally agnostic.
