### ISSUE TITLE
docker-compose weird messages

### ISSUE THREAD

**Issue by iOiurson** [anthill/pheromon#36]
I get these weird messages after some time with my container up ...
It doesn't seem to be much critical, but still we should take a look at it.

![capture d ecran 2015-09-21 a 13 59 45](https://cloud.githubusercontent.com/assets/8417814/9991292/2738fa04-6069-11e5-9037-1ff3373a3c1b.png)

**Comment by DavidBruant** [comment]
I have them as well from times to times. It looks like a docker-compose bug more than anything else.

**Comment by vallettea** [comment]
Everybody has them.
[This link](https://smartos.org/bugview/DOCKER-335) seems to relate this to certificate issues.
A quick fix locally si to set `DOCKER_CLIENT_TIMEOUT` to a higher value (default 60 sec)

**Comment by iOiurson** [comment]
Let's close this for now, the quick fix might be enough.
