### ISSUE TITLE
gulp task 'build' missing

### ISSUE THREAD

**Issue by SergeBredin** [anthill/pheromon#38]
gulp.task('build', ['build-dashboard', 'build-admin']);

**Comment by iOiurson** [comment]
Should be handled by #34

**Comment by iOiurson** [comment]
Can smb confirm this is resolved ?

**Comment by iOiurson** [comment]
Ok, this is not really available as such. Normally the build is automated if the bundle files are not found. But i will add this anyway, it might be useful somehow.

**Comment by iOiurson** [comment]
Closed by #48
