### ISSUE TITLE
Create more indexes in Pheromon DB

### ISSUE THREAD

**Issue by iOiurson** [anthill/pheromon#83]
## Sensors
- installed_at
- project
- sim

## Measurement
- output_id
- date

## Output
- sensor_id

**Comment by iOiurson** [comment]
We might need to add these indexes manually to avoid re initializing our pheromon db and losing our data.

**Comment by SergeBredin** [comment]
Done but 2 errors / 7 requests
ERROR:  relation "project" already exists
ERROR:  relation "type" already exists
Let see the dump of tomorrow...

**Comment by iOiurson** [comment]
These 2 indexes were already created... my bad.

**Comment by SergeBredin** [comment]
Indexes creation in the latest dump:

--
-- Name: date; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX date ON measurements USING btree (date);


--
-- Name: installed_at; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX installed_at ON sensors USING btree (installed_at);


--
-- Name: output_id; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX output_id ON measurements USING btree (output_id);


--
-- Name: project; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX project ON sensors USING btree (project);


--
-- Name: sensor_id; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX sensor_id ON outputs USING btree (sensor_id);


--
-- Name: sim; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX sim ON sensors USING btree (sim);


--
-- Name: type; Type: INDEX; Schema: public; Owner: postgres; Tablespace: 
--

CREATE INDEX type ON outputs USING btree (type);
